export const SET_HOME_DATA = 'SET_HOME_DATA';
export const SET_PERSONAL_DATA = 'SET_PERSONAL_DATA';

export const SET_TUTORIAL_DATA = 'SET_TUTORIAL_DATA';
export const SET_DECISION_DATA = 'SET_DECISION_DATA';
export const SET_FINANCIAL_DATA = 'SET_FINANCIAL_DATA';